services:
  api:
    container_name: sample-api-server
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    container_name: sample-api-postgresql
    image: postgres:12.14-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  
  pgadmin:
    container_name: sample-api-pgadmin
    image: dpage/pgadmin4:6.21
    restart: unless-stopped
    ports:
     - 5050:5050
    env_file:
     - .env
    volumes:
       - pgadmin:/var/lib/pgadmin


volumes:
  pgadmin:
  docker-nest-postgres:


